global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'analysis-service'
    static_configs:
      - targets: ['analysis-service:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'email-service'
    static_configs:
      - targets: ['email-service:8001']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'web-interface'
    static_configs:
      - targets: ['web-interface:8002']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s